publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /

credit:
    resource: "@CreditBundle/Resources/config/routing.yml"
    prefix:   /credits

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

security:
    resource: "@UGSecurityBundle/Resources/config/routing.yml"
    prefix:   /



