# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        UnaGauchada\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        users:
            entity: { class: UserBundle:User, property: email }

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                require_previous_session: false
            logout:
                path: /logout
                target: /
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }