# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        UnaGauchada\UserBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       7

    providers:
        users:
            entity: { class: UserBundle:User, property: email }

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /admin

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }