# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.security.publication_voter:
        class:  UnaGauchada\SecurityBundle\Security\PublicationVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
