credits_purchase:
    path:     /buy
    defaults: { _controller: CreditBundle:Credit:purchase }
    methods: [GET]

credits_buy:
    path:     /buy
    defaults: { _controller: CreditBundle:Credit:buy }
    methods: [POST]