credits_purchase_amount:
    path:     /buy/amount
    defaults: { _controller: CreditBundle:Credit:selectAmount }
    methods: [GET]

credits_purchase_info:
    path:     /buy/info
    defaults: { _controller: CreditBundle:Credit:userInfo }
    methods: [POST]

credits_buy:
    path:     /buy
    defaults: { _controller: CreditBundle:Credit:buy }
    methods: [POST]