login:
    path:   /login
    defaults:  { _controller: UGSecurityBundle:Security:login }

logout:
    path:   /logout

#signup:
#    path:   /signup
#    defaults:  { _controller: SecurityBundle:Security:signup }