login:
    path:   /login
    defaults:  { _controller: UGSecurityBundle:Security:login }

logout:
    path:   /logout

register:
    path:   /signup
    defaults:  { _controller: UGSecurityBundle:Security:register }
    methods:  [GET]

signup:
    path:   /signup
    defaults:  { _controller: UGSecurityBundle:Security:signup }
    methods:  [POST]

user_password_edit:
  path:       /user/changePassword
  defaults: { _controller: UGSecurityBundle:Security:editPassword }
  methods:  [GET]

user_password_change:
  path:       /user/changePassword
  defaults: { _controller: UGSecurityBundle:Security:changePassword }
  methods:  [POST]