user_photo:
    path:     /{id}/photo
    defaults: { _controller: UserBundle:User:photo }
    methods: [GET]

user_profile:
  path:       /profile
  defaults: { _controller: UserBundle:User:profile }

user_submissions:
  path:       /submissions
  defaults: { _controller: UserBundle:User:submissions }

user_profile_edit_show:
  path:       /profile/edit
  defaults: { _controller: UserBundle:User:editShow }
  methods:  [GET]

user_profile_edit:
  path:       /profile/edit
  defaults: { _controller: UserBundle:User:edit }
  methods:  [POST]