publication_page:
    path:     /page/{page}
    defaults: { _controller: PublicationBundle:Publication:index, page: 1 }
    methods: [GET]

publish_new:
    path:     /publish
    defaults: { _controller: PublicationBundle:Publication:publish }
    methods:  [GET]

publish_create:
    path:     /publish
    defaults: { _controller: PublicationBundle:Publication:publishCreate }
    methods:  [POST]

publication_search:
    path:     /search
    defaults: { _controller: PublicationBundle:Publication:search }
    methods:  [GET]

publication_image:
    path:     /{id}/image
    defaults: { _controller: PublicationBundle:Publication:image }
    methods:  [GET]

publication_show:
    path:     /{id}
    defaults: { _controller: PublicationBundle:Publication:show }
    methods:  [GET]

comment_create:
    path:     /{id}/comment
    defaults: { _controller: PublicationBundle:Publication:comment}
    methods:  [POST]

response_create:
    path:     /{id}/{comment}/response
    defaults: { _controller: PublicationBundle:Publication:response}
    methods:  [POST]

publication_submissions:
    path:     /{id}/submissions
    defaults: { _controller: PublicationBundle:Publication:submissions }
    methods:  [GET]

publication_submit:
    path:     /{id}/submit
    defaults: { _controller: PublicationBundle:Publication:submit}
    methods:  [POST]
