publication_homepage:
    path:     /
    defaults: { _controller: PublicationBundle:Publication:index }

publish_new:
    path:     /publish
    defaults: { _controller: PublicationBundle:Publication:publish }
    methods:  [GET]

publish_create:
    path:     /publish
    defaults: { _controller: PublicationBundle:Publication:publishCreate }
    methods:  [POST]

publication_image:
    path:     /publication/{id}/image
    defaults: { _controller: PublicationBundle:Publication:image }
    methods:  [GET]

publication_show:
    path:     /publication/{id}
    defaults: { _controller: PublicationBundle:Publication:show }
    methods:  [GET]