publication_homepage:
    path:     /
    defaults: { _controller: PublicationBundle:Publication:index }


publication:
    path:     /publication
    defaults: { _controller: PublicationBundle:Publication:publication }

publish:
    path:     /publish
    defaults: { _controller: PublicationBundle:Publication:publish }
