rating_report:
    path:     /rating
    defaults: { _controller: AdminBundle:Admin:rating }

credits_price:
    path:     /creditsPrice
    defaults: { _controller: AdminBundle:Admin:creditsPrice }

change_credits_price:
    path:     /changeCreditsPrice
    defaults: { _controller: AdminBundle:Admin:changeCreditsPrice }
    methods: [POST]