rating_report:
    path:     /rating
    defaults: { _controller: AdminBundle:Admin:rating }

achievements_management:
    path:     /achievements
    defaults: { _controller: AdminBundle:Admin:achievements }
