rating_report:
    path:     /rating
    defaults: { _controller: AdminBundle:Admin:rating }

achievements_management:
    path:     /achievements
    defaults: { _controller: AdminBundle:Admin:achievements }

edit_achievements:
    path:     /editAchievements
    defaults: { _controller: AdminBundle:Admin:editAchievements }
